# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54254ff7867bf47cbf17c50a9a73f20f9cf68a0dbc2c6f2818160c9e8c374d0ffd553bbbced7e1081ee2c1223315e08571106c81100800ddcdb82d4a2618c463
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  
test:
  secret_key_base: 81fa7065f073a2c7693dcda27542aff96968d868c4d45d5dc8a9c9981bdba36e090a5c46224409b9c71afd711839db483724339c219701dd848561af57f39027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>